spring:
  data:
    mongodb:
      uri: "mongodb://localhost:27017/baizhi"

# mongodb 有用户名密码
#spring.data.mongodb.host=tx.chenyn.cn
#spring.data.mongodb.port=27017
#spring.data.mongodb.database=baizhi
#spring.data.mongodb.username=root
#spring.data.mongodb.password=root

# mongo replica set
#spring.data.mongodb.uri=mongodb://tx.chenyn.cn:27017,tx.chenyn.cn:27018,tx.chenyn.cn:27019/baizhi?replicaSet=myreplace
